// 定义所有可用的角色
const ROLES = {
    SUPER_ADMIN: 'superadmin',        // 超级管理员
    PROVINCE_ADMIN: 'province_admin', // 省级管理员
    CITY_ADMIN: 'city_admin',         // 市级管理员
    DISTRICT_ADMIN: 'district_admin', // 区县级管理员
    ORGANIZATION_USER: 'organization_user' // 机构用户（原编辑员）
};

// 定义所有可用的权限 (推荐格式: 资源:操作)
const PERMISSIONS = {
    USERS_READ: 'users:read',
    USERS_WRITE: 'users:write',
    CARBON_DATA_READ: 'carbonData:read',
    CARBON_DATA_CREATE: 'carbonData:create',
    CARBON_DATA_UPDATE: 'carbonData:update',
    CARBON_DATA_DELETE: 'carbonData:delete',
    REPORTS_GENERATE: 'reports:generate',
    EMISSION_FACTORS_READ: 'emissionFactors:read',
    EMISSION_FACTORS_WRITE: 'emissionFactors:write'
};

// 核心！将权限分配给角色
const rolePermissions = {
    [ROLES.SUPER_ADMIN]: [ /* 超级管理员拥有所有权限... */
        PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE,
        PERMISSIONS.CARBON_DATA_READ, PERMISSIONS.CARBON_DATA_CREATE,
        PERMISSIONS.CARBON_DATA_UPDATE, PERMISSIONS.CARBON_DATA_DELETE,
        PERMISSIONS.REPORTS_GENERATE,
        PERMISSIONS.EMISSION_FACTORS_READ, PERMISSIONS.EMISSION_FACTORS_WRITE
    ],
    [ROLES.PROVINCE_ADMIN]: [ /* 省级管理员可以管理用户、查看和更新省级及以下数据 */
        PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE,
        PERMISSIONS.CARBON_DATA_READ, PERMISSIONS.CARBON_DATA_UPDATE,
        PERMISSIONS.CARBON_DATA_DELETE, PERMISSIONS.REPORTS_GENERATE,
        PERMISSIONS.EMISSION_FACTORS_READ, PERMISSIONS.EMISSION_FACTORS_WRITE
    ],
    [ROLES.CITY_ADMIN]: [ /* 市级管理员可以管理用户、查看和更新市级及以下数据 */
        PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE,
        PERMISSIONS.CARBON_DATA_READ, PERMISSIONS.CARBON_DATA_UPDATE,
        PERMISSIONS.CARBON_DATA_DELETE, PERMISSIONS.REPORTS_GENERATE,
        PERMISSIONS.EMISSION_FACTORS_READ, PERMISSIONS.EMISSION_FACTORS_WRITE
    ],
    [ROLES.DISTRICT_ADMIN]: [ /* 区县级管理员可以管理用户、查看和更新区级及以下数据 */
        PERMISSIONS.USERS_READ, PERMISSIONS.USERS_WRITE,
        PERMISSIONS.CARBON_DATA_READ, PERMISSIONS.CARBON_DATA_UPDATE,
        PERMISSIONS.CARBON_DATA_DELETE, PERMISSIONS.REPORTS_GENERATE,
        PERMISSIONS.EMISSION_FACTORS_READ, PERMISSIONS.EMISSION_FACTORS_WRITE
    ],
    [ROLES.ORGANIZATION_USER]: [ /* 机构用户可以读、写、更新、删除本机构碳数据和生成报告 */
        PERMISSIONS.CARBON_DATA_READ, PERMISSIONS.CARBON_DATA_CREATE,
        PERMISSIONS.CARBON_DATA_UPDATE, PERMISSIONS.CARBON_DATA_DELETE,
        PERMISSIONS.REPORTS_GENERATE, PERMISSIONS.EMISSION_FACTORS_READ
    ]
};

module.exports = {
    ROLES,
    PERMISSIONS,
    rolePermissions
};
